# Version of docker-compose
version: "3.4"

# Containers we are going to run
services:
  api:
    image: notebook-api
    # The build parameters for this container.
    # Here we define that it should build from the current directory
    build:
      context: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/notebooks:/apps/notebooks/
  nbs:
    image: notebook
    # The build parameters for this container.
    # Here we define that it should build from the current directory
    build:
      context: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/notebooks:/apps/notebooks/
    command: jupyter notebook --ip 0.0.0.0 --no-browser --port=8888 --allow-root --NotebookApp.token=''